on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: mahaplatform/docs.mahaplatform.com
      - name: Run build
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
