on: [push]

jobs:
  build:
    name: Build docsite
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: action/checkout@main
      - name: Run build
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
